// app
export const TOGGLE_DATE_FILTER = 'TOGGLE_DATE_FILTER';
export const SET_FOCUS = 'SET_FOCUS';
export const TOGGLE_FOCUS = 'TOGGLE_FOCUS';
export const SEARCH = 'SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';
export const SET_PROJECT_FILTER = 'SET_PROJECT_FILTER';

// projects
export const SET_PROJECTS = 'SET_PROJECTS';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const UP_PROJECT_FREQUENCY = 'UP_PROJECT_FREQUENCY';
export const DOWN_PROJECT_FREQUENCY = 'DOWN_PROJECT_FREQUENCY';
export const SET_PROJECT_STATUS = 'SET_PROJECT_STATUS';

// focusItems
export const SET_FOCUS_ITEMS = 'SET_FOCUS_ITEMS';
export const ADD_FOCUS_ITEM = 'ADD_FOCUS_ITEM';
export const EDIT_FOCUS_ITEM = 'EDIT_FOCUS_ITEM';
export const DELETE_FOCUS_ITEM = 'DELETE_FOCUS_ITEM';
export const MARK_DONE_FOCUS_ITEM = 'MARK_DONE_FOCUS_ITEM';
export const INC_START_DATE_FOCUS_ITEM = 'INC_START_DATE_FOCUS_ITEM';
export const INC_DUE_DATE_FOCUS_ITEM = 'INC_DUE_DATE_FOCUS_ITEM';
export const DEC_START_DATE_FOCUS_ITEM = 'DEC_START_DATE_FOCUS_ITEM';
export const DEC_DUE_DATE_FOCUS_ITEM = 'DEC_DUE_DATE_FOCUS_ITEM';
export const REMOVE_DATE_FOCUS_ITEM = 'REMOVE_DATE_FOCUS_ITEM';
export const PICK_NEXT_FOCUS_ITEM = 'PICK_NEXT_FOCUS_ITEM';
export const NEXT_CATEGORY_FOCUS_ITEM = 'NEXT_CATEGORY_FOCUS_ITEM';
