export const TOGGLE_DATE_FILTER = 'TOGGLE_DATE_FILTER';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const UP_PROJECT_FREQUENCY = 'UP_PROJECT_FREQUENCY';
export const DOWN_PROJECT_FREQUENCY = 'DOWN_PROJECT_FREQUENCY';
export const SET_PROJECT_STATUS = 'SET_PROJECT_STATUS';
